In [1]:
import numpy as np

In [2]:
M = np.array([[1,3],[4,7]])

In [3]:
L =[[1,3],[4,7]]

In [4]:
L[0]

[1, 3]

In [5]:
L[0][0]

1

In [8]:
M[0]

array([1, 3])

In [9]:
M[0][0]

1

In [10]:
M[0,0]

1

In [12]:
M[1,1]

7

In [15]:
M2 = np.matrix([[1,3],[4,7]])
M2

matrix([[1, 3],
        [4, 7]])

In [16]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
Z = np.zeros([5,5])
Z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
R = np.random.random([4,4])
R

array([[ 0.25770315,  0.84785172,  0.35888625,  0.636471  ],
       [ 0.93872265,  0.68932116,  0.95485535,  0.57704666],
       [ 0.1487629 ,  0.44939631,  0.11041574,  0.41879722],
       [ 0.70052296,  0.9352605 ,  0.5309753 ,  0.49953055]])

In [24]:
R = np.random.random((4,4))
R

array([[ 0.4729338 ,  0.53641184,  0.73328189,  0.26148232],
       [ 0.56049603,  0.19122052,  0.88319024,  0.01083671],
       [ 0.10443226,  0.59524943,  0.57392863,  0.28460624],
       [ 0.65248692,  0.47249528,  0.02187562,  0.00424836]])

In [25]:
type(R)

numpy.ndarray

In [26]:
G = np.random.randn(10,10)
G

array([[ -3.98550157e-02,   1.12204671e+00,   5.21327649e-01,
          1.09925460e+00,  -5.70002637e-01,  -1.16881378e+00,
          7.63986882e-01,  -3.28372457e-01,   2.15381290e-01,
         -5.32777608e-01],
       [  1.27692396e+00,  -1.96904176e+00,  -8.83582299e-01,
          7.11504979e-02,  -1.36103446e+00,   1.25836717e+00,
          6.83428573e-01,  -7.23325257e-01,   8.25296365e-03,
          8.43237529e-01],
       [  2.00287132e+00,   1.48885938e-01,   1.29681778e+00,
          2.33785798e+00,   2.91853658e-01,  -1.26485901e+00,
          7.00205183e-01,   3.93104998e-01,  -3.09208930e+00,
         -1.28556951e+00],
       [ -2.08455819e-01,   2.13781164e+00,   4.00688653e-01,
          5.46583787e-01,   7.85665001e-01,  -1.91556195e-01,
          9.95604374e-02,  -2.07073949e+00,  -3.00675112e+00,
          1.70774039e-03],
       [ -1.38569053e+00,  -6.50720995e-01,  -7.16257109e-01,
          5.27380531e-01,  -3.50028232e-01,   7.06080455e-01,
          9.05981580e-01

In [27]:
G.mean()

0.018443695497101398

In [28]:
G.var()

1.2392580316366231

In [30]:
A = np.array([[1,2],[3,5]])
A

array([[1, 2],
       [3, 5]])

In [34]:
Ainv = np.linalg.inv(A)
Ainv

array([[-5.,  2.],
       [ 3., -1.]])

In [35]:
Ainv.dot(A)

array([[  1.00000000e+00,   1.77635684e-15],
       [  0.00000000e+00,   1.00000000e+00]])

In [36]:
A.dot(Ainv)

array([[  1.00000000e+00,   2.22044605e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [37]:
np.linalg.det(A)

-1.0000000000000004

In [38]:
np.diag(A)

array([1, 5])

In [39]:
a = np.array([1,2])

In [40]:
b = np.array([3,4])

In [41]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [42]:
np.outer(b,a)

array([[3, 6],
       [4, 8]])

In [43]:
np.inner(a,b)

11

In [44]:
np.inner(b,a)

11

In [45]:
np.dot(a,b)

11

In [46]:
np.diag(A).sum()

6

In [47]:
np.trace(A)

6

In [49]:
X = np.random.randn(100,3)

In [50]:
cov = np.cov(X)

In [51]:
cov = np.cov(X.T)
cov

array([[ 0.81978774, -0.07116813,  0.04279438],
       [-0.07116813,  1.09758796,  0.15001036],
       [ 0.04279438,  0.15001036,  0.95089404]])

In [52]:
np.linalg.eigh(cov)

(array([ 0.76013035,  0.91295717,  1.19518222]),
 array([[ 0.79357726, -0.59944781, -0.10439086],
        [ 0.3789754 ,  0.35271533,  0.85555218],
        [-0.47603863, -0.71850833,  0.50708284]]))

In [53]:
np.linalg.eig(cov)

(array([ 0.76013035,  0.91295717,  1.19518222]),
 array([[-0.79357726, -0.59944781, -0.10439086],
        [-0.3789754 ,  0.35271533,  0.85555218],
        [ 0.47603863, -0.71850833,  0.50708284]]))

In [54]:
a

array([1, 2])

In [55]:
A

array([[1, 2],
       [3, 5]])

In [58]:
A[1,1]=4
A

array([[1, 2],
       [3, 4]])

In [60]:
b = a

In [61]:
b

array([1, 2])

In [65]:
x = np.linalg.inv(A).dot(b)
x

array([  2.22044605e-16,   5.00000000e-01])

In [64]:
x = np.linalg.solve(A,b)
x

array([ 0. ,  0.5])

In [66]:
A

array([[1, 2],
       [3, 4]])