In [11]:
import numpy as np

In [15]:
"""
The admission fee at a small fair is $1.50 for children and $4.00 for 
adults. On a certainday, 2200 people enter the fair and $5050 is collected.
How many children and how many adults attended?

Let:
X1 = number of children & X2 = number of adults

X1 + X2 = 2200
1.5*X1 + 4*X2 = 5050

[1,1;1.5,4]*[X1;X2] = [2200;5050]

"""

'\nThe admission fee at a small fair is $1.50 for children and $4.00 for \nadults. On a certainday, 2200 people enter the fair and $5050 is collected.\nHow many children and how many adults attended?\n\nLet:\nX1 = number of children & X2 = number of adults\n\nX1 + X2 = 2200\n1.5*X1 + 4*X2 = 5050\n\n[1,1;1.5,4]*[X1;X2] = [2200;5050]\n\n'

In [7]:
A = np.array([[1,1],[1.5,4]])
A

array([[ 1. ,  1. ],
       [ 1.5,  4. ]])

In [5]:
b = np.array([2200,5050])
b

array([2200, 5050])

In [6]:
np.linalg.solve(A,b)

array([ 1500.,   700.])